---
# tasks file for bonita_dev

## include OS family specific variables and custom facts

- name: include OS family/distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/defaults/{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}.yml"
    - "{{ role_path }}/defaults/{{ ansible_os_family | lower }}.yml"
  tags: [ installation ]

- name: Create tenant admin random password
  set_fact:
    cacheable: false
    tenant_admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=10' ) }}"
  tags: [ installation ]

## run

- name: check host environment
  include: check_environment.yml

- include: debug.yml
  when: debug | default(false)
  tags: [ debug ]

## include OS family/distribution specific task file

- name: include OS family/distribution specific task file
  include: "{{ item }}"
  with_first_found:
    - "installation/{{ ansible_os_family | lower }}/{{ ansible_distribution | lower }}_{{ ansible_distribution_version | lower }}.yml"
    - "installation/{{ ansible_os_family | lower }}/{{ ansible_distribution | lower }}.yml"
    - "installation/{{ ansible_os_family | lower }}/main.yml"
  tags: [ installation ]
