---
# tasks file for bonita_dev

- name: debian | Check if current configuration exists.
  stat:
    path: "{{ bonita_install_dir }}/setup/platform_conf/current"
  register: current_conf

- name: set fact non_first_run
  set_fact:
    non_first_run={{ current_conf.stat.exists and current_conf.stat.isdir }}

# -- First run case
- name: debian | Configure admin username
  replace:
    path: "{{ bonita_install_dir }}/setup/platform_conf/initial/tenant_template_engine/bonita-tenant-community-custom.properties"
    regexp: '^#userName=.*$'
    replace: 'userName=Install'
  when: not non_first_run
- name: debian | Configure admin password
  replace:
    path: "{{ bonita_install_dir }}/setup/platform_conf/initial/tenant_template_engine/bonita-tenant-community-custom.properties"
    regexp: '^#userPassword=.*$'
    replace: "userPassword={{ tenant_admin_password }}"
  when: not non_first_run

- name: debian | Configure admin default username
  replace:
    path: "{{ bonita_install_dir }}/setup/platform_conf/initial/platform_portal/platform-tenant-config.properties"
    regexp: '^platform\.tenant\.default\.username=.*$'
    replace: 'platform.tenant.default.username=Install'
  when: not non_first_run
- name: debian | Configure admin default password
  replace:
    path: "{{ bonita_install_dir }}/setup/platform_conf/initial/platform_portal/platform-tenant-config.properties"
    regexp: '^platform\.tenant\.default\.password=.*$'
    replace: "platform.tenant.default.password={{ tenant_admin_password }}"
  when: not non_first_run

# -- Non first run case
- name: debian | Configure admin username
  replace:
    path: "{{ bonita_install_dir }}/setup/platform_conf/current/tenant_template_engine/bonita-tenant-community-custom.properties"
    regexp: '^#userName=.*$'
    replace: 'userName=Install'
  when: non_first_run
- name: debian | Configure admin password
  replace:
    path: "{{ bonita_install_dir }}/setup/platform_conf/current/tenant_template_engine/bonita-tenant-community-custom.properties"
    regexp: '^#userPassword=.*$'
    replace: "userPassword={{ tenant_admin_password }}"
  when: non_first_run

- name: debian | Configure admin default username
  replace:
    path: "{{ bonita_install_dir }}/setup/platform_conf/current/platform_portal/platform-tenant-config.properties"
    regexp: '^platform\.tenant\.default\.username=.*$'
    replace: 'platform.tenant.default.username=Install'
  when: non_first_run
- name: debian | Configure admin default password
  replace:
    path: "{{ bonita_install_dir }}/setup/platform_conf/current/platform_portal/platform-tenant-config.properties"
    regexp: '^platform\.tenant\.default\.password=.*$'
    replace: "platform.tenant.default.password={{ tenant_admin_password }}"
  when: non_first_run

#- name: debian | Push current configuration
#  shell: "nohup {{ bonita_install_dir }}/setup/setup.sh push ;"
#  args:
#    chdir: "{{ bonita_install_dir }}"
#  when: non_first_run
#  tags: [ installation ]